title: Doctored
description: "A  blog theme prioritizing uniqueness, complexity, and sophistication."
github: "https://github.com/matmanna/doctored"
url: "https://doctored.matmanna.dev/"
color: stone
encoding: utf-8

plugins:
  - kramdown-parser-gfm
  - jekyll-gfm-admonitions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-git
  - jekyll-seo-tag
  - jekyll/tagging

feed:
  icon: /assets/images/favicon.png

redcarpet:
  extensions: ["with_toc_data"]

tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag

related_from: posts projects
related_by: tags categories
related_template: post-card.html

collections:
  projects:
    output: true
  pages:
    permalink: /:title/
    output: true

exclude: 
- README.md
- LICENSE
- "*.gem"
- "*.gemspec"
- vendor
- Gemfile.lock
- .gitignore
- bin
- node_modules
- package-lock.json
- tailwind.config.js
- .github

keep_files:
  - assets/css/tailwind.css
  - assets/css/main.*.css
  - assets/js
